# Generated by Django 4.2.5 on 2024-10-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0004_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(help_text='Введите Вашу электронную почту', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
