# Generated by Django 4.2.5 on 2024-10-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0005_alter_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='status_role',
            new_name='status_rule',
        ),
    ]
